OnlineStore.WebUI/Models/ProductSummaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using OnlineStore.WebUI.ApplicationData;

namespace OnlineStore.WebUI.Models
{
    public class ProductSummaryViewModel
    {
        public SaleProduct SaleProduct { get; set; }
        public AssetAllocation AssetAllocation { get; set; }
        public bool InStock { get; set; }
    }
}

OnlineStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Configuration;
using System.Net;
using OnlineStore.WebUI.Models;
using OnlineStore.WebUI.ApplicationData;
using OnlineStore.WebUI.Infrastructure;

namespace OnlineStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private ApplicationData.ApplicationData applicationDataContext;
        private WMSData.WMSData wmsDataContext;

        public CartController()
        {
            string username = WebConfigurationManager.AppSettings["Username"];
            string password = WebConfigurationManager.AppSettings["Password"];

            NetworkCredential credentials = new NetworkCredential(username, password);

            if(applicationDataContext == null)
            {
                Uri applicationDataUri = new Uri(WebConfigurationManager.AppSettings["ApplicationDataUri"]);
                applicationDataContext = new ApplicationData.ApplicationData(applicationDataUri);
                applicationDataContext.Credentials = credentials;
            }

            if (wmsDataContext == null)
            {
                Uri wmsDataUri = new Uri(WebConfigurationManager.AppSettings["WMSDataUri"]);
                wmsDataContext = new WMSData.WMSData(wmsDataUri);
                wmsDataContext.Credentials = credentials;
            }
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                ReturnUrl = returnUrl,
                Cart = cart
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int id, int? assetAllocationId, string returnUrl)
        {
            SaleProduct sp = applicationDataContext.SaleProducts.Expand("Product, Sale").Where(x => x.Id == id).FirstOrDefault();

            AssetAllocation aa = null;

            if (assetAllocationId.HasValue)
            {
                aa = applicationDataContext.AssetAllocations.Where(x => x.Id == assetAllocationId).Single();
            }

            if (sp != null)
            {
                cart.AddItem(sp, 1, aa);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int id,
                string returnUrl)
        {
            SaleProduct saleProduct = applicationDataContext.SaleProducts.Where(x => x.Id == id).FirstOrDefault();

            if (saleProduct != null)
            {
                cart.RemoveLine(saleProduct);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout(Cart cart)
        {
            ShippingDetailsViewModel model = new ShippingDetailsViewModel();

            if (cart.Lines.Count() != 0)
            {
                var assetAllocation = cart.Lines.First().AssetAllocation;

                if (assetAllocation != null)
                {
                    model.Email = assetAllocation.EmployeeEmail;
                }
            }
            
            return View(model);
        }

        [HttpPost]
        public ActionResult Checkout(Cart cart, ShippingDetailsViewModel shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                OrderProcessor processor = new OrderProcessor(applicationDataContext, cart, shippingDetails);
                return Redirect(processor.ProcessOrder());
            }
            else
            {
                return View(shippingDetails);
            }
        }
    }
}

OnlineStore.WebUI/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Configuration;
using System.Web.Helpers;
using System.Net;
using OnlineStore.WebUI.Models;
using System.Configuration;


namespace OnlineStore.WebUI.Controllers
{
    public class CustomerController : Controller
    {
        private ApplicationData.ApplicationData applicationDataContext;
        private WMSData.WMSData wmsDataContext;

        public CustomerController()
        {
            string username = WebConfigurationManager.AppSettings["Username"];
            string password = WebConfigurationManager.AppSettings["Password"];

            NetworkCredential credentials = new NetworkCredential(username, password);

            if(applicationDataContext == null)
            {
                Uri applicationDataUri = new Uri(WebConfigurationManager.AppSettings["ApplicationDataUri"]);
                applicationDataContext = new ApplicationData.ApplicationData(applicationDataUri);
                applicationDataContext.Credentials = credentials;
            }

            if (wmsDataContext == null)
            {
                Uri wmsDataUri = new Uri(WebConfigurationManager.AppSettings["WMSDataUri"]);
                wmsDataContext = new WMSData.WMSData(wmsDataUri);
                wmsDataContext.Credentials = credentials;
            }
        }

        public ActionResult Welcome(string customerCode, string saleId)
        {
            var customer = applicationDataContext.Customers.Where(x => x.CustomerCode == customerCode).SingleOrDefault();
            var sale = applicationDataContext.Sales.Where(x => x.Customer.CustomerCode == customerCode).SingleOrDefault();

            WelcomeViewModel model = new WelcomeViewModel { Customer = customer, Sale = sale };

            if(customer != null)
            {
                Session["CustomerName"] = customer.CustomerName;
                Session["CustomerCode"] = customer.CustomerCode;
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Welcome(WelcomeViewModel model,string Salecode)
        {
            var customer = applicationDataContext.Customers.Where(x => x.Id == model.Customer.Id).Single();
            var sale = applicationDataContext.Sales.Where(x => x.Id == model.Sale.Id).Single();

            if (sale.SaleType == "Pre-Allocated")
            {
                if (string.IsNullOrEmpty(model.EmployeeEmail))
                {
                    ModelState.AddModelError("EmployeeEmail", "Please enter an email address");
                }

                if (string.IsNullOrEmpty(model.EmployeeID))
                {
                    ModelState.AddModelError("EmployeeID", "Please enter your employee ID");
                }

                if (ModelState.IsValid)
                {
                    var assetAllocations = applicationDataContext.AssetAllocations.Where(x => x.EmployeeEmail == model.EmployeeEmail && x.EmployeeID == model.EmployeeID);

                    if (assetAllocations.Count() == 0)
                    {
                        ModelState.AddModelError(string.Empty, "Employee not found");
                    }
                }

                Session["employeeId"] = model.EmployeeID;
            }

           // string salesCode = Salecode.ToString();
           //if (string.IsNullOrEmpty(salesCode))
           // {
           //     ModelState.AddModelError("Sale Code", "Please enter Sale Code");
           //     Session["ErrorMessage"] = "Please enter Sale Code";

           // }
           //if(!string.IsNullOrEmpty(salesCode) && salesCode != sale.SaleID)
           // {
           //     ModelState.AddModelError("Sale Code", "Sale Code Not Matched!");

           //     Session["ErrorMessage"]="Sale Code Not Matched!";

           // }
            if (ModelState.IsValid)
            {
                return RedirectToAction("List", "Sale", new { customerCode = customer.CustomerCode, saleId = sale.SaleID });
             }

            model.Customer = customer;
            model.Sale = sale;

            return View(model);
        }

        public ActionResult GetCustomerLogo(int customerId)
        {
            string encoding = "image/jpg";
            WebImage image = new WebImage("~/Content/Images/verserlogo.png");

            var customer = applicationDataContext.Customers.Where(x => x.Id == customerId).SingleOrDefault();

            if(customer != null)
            {
                var logo = customer.Logo;

                if(logo != null && logo.Length > 0)
                {
                    image = new WebImage(logo);

                    switch (image.ImageFormat)
                    {
                        case "jpeg":
                            encoding = "image/jpg";
                            break;
                        case "png":
                            encoding = "image/png";
                            break;
                    }
                }
            }

            return File(image.GetBytes(), encoding);
        }
    }
}

OnlineStore.WebUI/Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Helpers;
using System.Net;
using System.Web.Configuration;
using OnlineStore.WebUI.Models;
using OnlineStore.WebUI.ApplicationData;

namespace OnlineStore.WebUI.Controllers
{
    public class SaleController : Controller
    {
        private ApplicationData.ApplicationData applicationDataContext;
        private WMSData.WMSData wmsDataContext;

        public SaleController()
        {
            string username = WebConfigurationManager.AppSettings["Username"];
            string password = WebConfigurationManager.AppSettings["Password"];

            NetworkCredential credentials = new NetworkCredential(username, password);

            if(applicationDataContext == null)
            {
                Uri applicationDataUri = new Uri(WebConfigurationManager.AppSettings["ApplicationDataUri"]);
                applicationDataContext = new ApplicationData.ApplicationData(applicationDataUri);
                applicationDataContext.Credentials = credentials;
            }

            if (wmsDataContext == null)
            {
                Uri wmsDataUri = new Uri(WebConfigurationManager.AppSettings["WMSDataUri"]);
                wmsDataContext = new WMSData.WMSData(wmsDataUri);
                wmsDataContext.Credentials = credentials;
            }
        }

        public ActionResult List(string itemType, string customerCode, string saleId)
        {
            var sale = applicationDataContext.Sales.Where(x => x.SaleID == saleId).Single();

            string employeeId = string.Empty;

            if (Session["EmployeeID"] != null)
                employeeId = Session["EmployeeID"].ToString();

            decimal? itemTypeId = null;

            if(!String.IsNullOrEmpty(itemType))
            {
                var i = wmsDataContext.ItemTypes.Where(x => x.Description == itemType).SingleOrDefault();

                if(i != null)
                {
                    itemTypeId = i.ID;
                }
            }

            List<SaleProductInfo> saleProductInfos;

            if (!string.IsNullOrEmpty(employeeId) && sale.SaleType == "Pre-Allocated")
            {
                saleProductInfos = applicationDataContext.AssetAllocations.Expand("Sale, SaleProduct, SaleProduct/Product, Order").Where(x => x.Sale.SaleID == saleId && x.EmployeeID == employeeId && x.Order == null).ToList().Select(x => new SaleProductInfo { SaleProduct = x.SaleProduct, AssetAllocation = x, InStock = true }).ToList();
            }
            else
            {
                saleProductInfos = applicationDataContext.SaleProducts.Expand("Product").Where(x => x.Sale.SaleID == saleId).ToList().Select(x => new SaleProductInfo { SaleProduct = x, InStock = x.QtyAvailable > 0 }).ToList();
            }

            if(itemTypeId.HasValue)
            {
                saleProductInfos = saleProductInfos.Where(x => x.SaleProduct.Product.ItemType_ID == itemTypeId).ToList();
            }

            var customer = applicationDataContext.Customers.Where(x => x.CustomerCode == customerCode).SingleOrDefault();

            if(customer != null)
            {
                Session["CustomerName"] = customer.CustomerName;
                Session["CustomerCode"] = customer.CustomerCode;
                Session["SaleID"] = saleId;
            }

            ProductsListViewModel model = new ProductsListViewModel {
                SaleProductInfos = saleProductInfos.AsEnumerable(),
                SelectedItemType = itemType,
                Customer = customer,
                SaleId = saleId
            };

            return View(model);
        }

        public ActionResult GetProductImage(int productId)
        {
            string encoding = "image/jpg";
            WebImage image = new WebImage("~/Content/Images/no_product_image.jpg");

            var product = applicationDataContext.Products.Where(x => x.Id == productId).SingleOrDefault();

            if (product != null)
            {
                var productImage = product.ProductImage;

                if (productImage != null && productImage.Length > 0)
                {
                    image = new WebImage(productImage);

                    switch (image.ImageFormat)
                    {
                        case "jpeg":
                            encoding = "image/jpg";
                            break;
                        case "png":
                            encoding = "image/png";
                            break;
                    }
                }
            }

            return File(image.GetBytes(), encoding);
        }

        [HttpPost]
        public ActionResult PaymentReceipt()
        {
            string username = Request.Form["username"];
            string password = Request.Form["password"];
            int orderNo = Convert.ToInt32(Request.Form["payment_reference"]);
            decimal paymentAmount = Convert.ToDecimal(Request.Form["am_payment"]);
            string cardType = Request.Form["nm_card_scheme"];
            string nameOnCard = Request.Form["nm_card_holder"];
            string truncatedCardNumber = Request.Form["TruncatedCardNumber"];
            int paymentStatus = Convert.ToInt32(Request.Form["fl_success"]);

            if (username != WebConfigurationManager.AppSettings["payway_username"] || password != WebConfigurationManager.AppSettings["payway_password"])
            {
                return new HttpUnauthorizedResult();
            }

            var order = applicationDataContext.Orders.Where(x => x.OrderNo == orderNo).Single();

            Payment payment = new Payment
            {
                Order = order,
                PaymentAmount = paymentAmount,
                CardType = cardType,
                NameOnCard = nameOnCard,
                TruncatedCardNo = truncatedCardNumber,
                PaymentStatus = paymentStatus
            };

            applicationDataContext.AddToPayments(payment);
            order.Payments.Add(payment);
            applicationDataContext.AddLink(order, "Payments", payment);

            applicationDataContext.SaveChanges(System.Data.Services.Client.SaveChangesOptions.Batch);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }
        
    }
}

OnlineStore.WebUI/Views/Shared/ProductSummary.cshtml
@model OnlineStore.WebUI.Models.ProductSummaryViewModel

@*<div class="well" style="min-height:220px">
    <h4 class="text-center" style="width:100px!important; float:left; margin-top:0">
        @if (Model.SaleProduct.Product.ProductImage != null)
        {
            <img class="img-thumbnail" width="80" height="80" src="@Url.Action("GetProductImage", "Sale", new { productId = Model.SaleProduct.Product.Id})" />
        }
    </h4>
    
    <div class="col-xs-8">
        <h4 style="margin-top:5px"><b>@Model.SaleProduct.Product.ProductName</b></h4>
        <p>@Html.Raw(@Model.SaleProduct.Product.Description)</p>
        @if (Model.SaleProduct.Product.ItemType_ID != 21)
        {
            <p><a href="https://payments.verser.com.au/OnlineStore/Home/FAQ" target="_blank">Find out more about refurbished ex-lease products</a></p>
        }
    </div>
    
    <div class="col-xs-2">
        <h4 style="margin-top:5px; padding-right:5px">
            <span>@Model.SaleProduct.PriceIncGST.Value.ToString("c")</span>
            <br/>
            
            <span style="font-size:small">Inc.GST</span>
        </h4>
        <br/>
        <div style="padding-right:5px">
            @if (Model.InStock)
            {
                <span class="text-success">In Stock</span>
            }
            else
            {
                <span class="text-danger">Out of Stock</span>
            }
        </div>
        <br />
        <br />
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div class="panel">
                @Html.Hidden("id", Model.SaleProduct.Id)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" class="btn btn-success" value="Add to Cart" @(Model.InStock ? "" : "disabled") />
            </div>
        }
    </div>
</div>*@

<div class="container well" style="border:1px solid lightGrey">
    <div class="row">
        <div class="col-md-2 text-center">
            @if (Model.SaleProduct.Product.ProductImage != null)
            {
                <img class="img-thumbnail" width="120" height="120" style="margin-bottom:15px" src="@Url.Action("GetProductImage", "Sale", new { productId = Model.SaleProduct.Product.Id})" />
            }
            else
            {
                <img src="~/Content/Images/no_image_available.jpg" width="120" height="120" style="margin-bottom:15px" />
               
            }
        </div>
        <div class="col-md-7">
            <h4 style="margin-top:5px"><b>@Model.SaleProduct.Product.ProductName</b></h4>

            @if (Model.AssetAllocation != null)
            {
                <div><b>Employee ID:</b> @Model.AssetAllocation.EmployeeID</div>
                <div><b>@Model.AssetAllocation.AssetID_Type:</b> @Model.AssetAllocation.AssetID</div>
                <br />
            }

            <p>@Html.Raw(@Model.SaleProduct.Product.Description)</p>

            @if (Model.SaleProduct.Product.ItemType_ID != 21)
            {
                @*<p><a href="https://payments.verser.com.au/OnlineStore/Home/FAQ" target="_blank">Find out more about refurbished ex-lease products</a></p>*@
            }
            <input type="checkbox" style="width: 20px;height:16px;" id="chkboxConfirm"/> <b style="font-weight:800;height:20px;vertical-align:top">
            The Serial No @Model.AssetAllocation.AssetID Must Match With The Serial Number provided to Verser By DET. If itdoes not then we need to replace the line highlighted above with.
          @*I DO Confirm that  Serial No @Model.AssetAllocation.AssetID Matches To My physical Serial No.*@
            </b>
        </div>
        <div class="col-md-3">
            <h4 style="margin-top:5px; padding-right:5px">
                <span>@Model.SaleProduct.PriceIncGST.Value.ToString("c")</span>

                <span style="font-size:x-small">Inc.GST</span>
                <br />
                @*@if (Model.InStock)
                    {
                        <span class="text-success" style="font-size:small">In Stock</span>
                    }
                    else
                    {
                        <span class="text-danger" style="font-size:small">Out of Stock</span>
                        <br />
                        <span style="font-size:small">Please check again soon</span>
                    }*@
            </h4>

            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.Hidden("id", Model.SaleProduct.Id)

                if (Model.AssetAllocation != null)
                {
                    @Html.Hidden("assetAllocationId", Model.AssetAllocation.Id)
                }

                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)

                <input id="btnAddToCart" type="@(Model.InStock ? "submit" : "hidden")" class="btn btn-success" value="Add to Cart" />
            }
        </div>
    </div>
    

</div>
<script>
    $(document).ready(function () {
        $("#btnAddToCart").attr("disabled", !($(this).is(":checked")));
        });
    $('#chkboxConfirm').change(function () {
            $("#btnAddToCart").attr("disabled", !($(this).is(":checked")));
    });
</script>

OnlineStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <script type="text/javascript" src="~/Scripts/jquery-1.10.2.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.js"></script>
    <style type="text/css">
        * {
            margin: 0;
        }
        html, body {
            height: 100%;
            
            
        }
        
        .wrapper {
            min-height: 100%;
            height: auto !important;
            height: 100%;
            margin: 0 auto -30px;
        }
        .my_footer, .push {
            clear: both;
            height: 20px;
            padding: 10px;
        }
    </style>
    <title>@ViewBag.Title</title>
</head>
<body>
    @{
        if (Session["CustomerName"] == null)
        {
            Session["CustomerName"] = "Online Store";
        }
    }

    <div class="wrapper">
        <div class="navbar navbar-default">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               @if (Session["SaleID"] != null)
               {
                <a class="navbar-brand" href="@Url.Action("List", "Sale", new { customerCode = Session["CustomerCode"], saleId = Session["SaleID"]})">@Session["CustomerName"]</a>
               }
               else
               {
                <a class="navbar-brand" href="@Url.Action("Welcome", "Customer", new { customerCode = Session["CustomerCode"] })">@Session["CustomerName"]</a>
                
                }
                <a href=""></a>

            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li id="faq">@Html.ActionLink("FAQ", "FAQ", "Home")</li>
        @* <li id="terms">@Html.ActionLink("Terms", "Terms", "Home")</li>
        <li id="upgrade">@Html.ActionLink("Windows 7 Professional", "Upgrade", "Home")</li>*@
                    <li id="contactUs">@Html.ActionLink("CONTACT US", "ContactUs", "Home")</li>
                </ul>

                <div>
                    @Html.Action("Summary", "Cart")
                </div>
            </div>
        </div>

        <div style="margin-top: 10px; margin-left: 10px;">
            @RenderBody()
        </div>
        <div class="push"></div>
    </div>
    <div class="my_footer text-center text-muted">
        The @Session["CustomerName"] site is managed by Verser Technology Lifecycles &copy; @DateTime.Now.Year
    </div>
</body>
</html>

OnlineStore.WebUI/Views/Shared/_MainContent.cshtml
@{
    ViewBag.Title = "_MainContent";
}

<h2>_MainContent</h2>